# Generated by Django 5.2.8 on 2025-11-19 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, help_text='Рост в см', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Вес в кг', null=True)),
                ('fitness_goal', models.CharField(choices=[('weight_loss', '📉 Похудение'), ('muscle_gain', '💪 Набор мышечной массы'), ('endurance', '🏃 Выносливость'), ('general_fitness', '🌟 Общая физическая форма')], default='general_fitness', max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20)),
                ('daily_calorie_target', models.IntegerField(default=2000)),
                ('protein_target', models.IntegerField(default=150, help_text='Грамм в день')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
