# Generated by Django 5.2.8 on 2025-11-19 15:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('workout_type', models.CharField(choices=[('home_strength', '💪 Домашняя сила'), ('home_cardio', '🏃 Домашнее кардио'), ('gym_strength', '🏋️ Силовая в зале'), ('gym_cardio', '🚴 Кардио в зале'), ('yoga', '🧘 Йога и растяжка')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', '🟢 Начинающий'), ('intermediate', '🟡 Средний'), ('advanced', '🔴 Продвинутый')], max_length=20)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Длительность в минутах')),
                ('calories_burned', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='workouts/')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sets', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('reps', models.CharField(help_text='Например: 10-12 или 30 секунд', max_length=50)),
                ('rest_time', models.IntegerField(default=60, help_text='Отдых в секундах')),
                ('equipment', models.CharField(choices=[('none', 'Без оборудования'), ('dumbbells', 'Гантели'), ('barbell', 'Штанга'), ('resistance_bands', 'Эспандеры'), ('yoga_mat', 'Коврик'), ('machine', 'Тренажер')], default='none', max_length=20)),
                ('demonstration_url', models.URLField(blank=True, help_text='Ссылка на видео демонстрацию')),
                ('order', models.IntegerField(default=0)),
                ('target_muscles', models.CharField(blank=True, max_length=200)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('completed_exercises', models.IntegerField(default=0)),
                ('total_sets', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_sets', models.IntegerField(default=0)),
                ('completed_reps', models.JSONField(default=dict)),
                ('weight_used', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='workouts.workoutsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['workout_type', 'difficulty'], name='workouts_wo_workout_e60c90_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['is_public', 'created_at'], name='workouts_wo_is_publ_b02fb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('workout', 'order')},
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'start_time'], name='workouts_wo_user_id_a46e10_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciselog',
            index=models.Index(fields=['session', 'exercise'], name='workouts_ex_session_c11484_idx'),
        ),
    ]
